import Head from "next/head";
import styles from "@/styles/Home.module.css";
import MusicList from "@/components/MusicList";
import styled from "styled-components";
import { MelonChartList } from "@/types/melon.type";
import { baseUrl } from "./api/melon/baseUrl";

export default function Home({ initialData }: { initialData: MelonChartList }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Background>
        <HeaderContainer>🎶 실시간 노래 차트 🎶</HeaderContainer>
        <main className={styles.main}>
          <MusicList initialData={initialData} />
        </main>
      </Background>
    </>
  );
}

export async function getStaticProps() {
  try {
    const response = await baseUrl.get(`/chart/day`);
    const initialData = Object.values(response.data);

    return {
      props: { initialData },
      revalidate: 3600, // 1시간마다 재생성
    };
  } catch (error) {
    console.error("데이터 가져오기 실패:", error);

    return {
      props: { initialData: [] },
      revalidate: 3600,
    };
  }
}

export const Background = styled.div`
  display: flex;
  flex-direction: column;
  width: 100%;
`;

export const HeaderContainer = styled.div`
  display: flex;
  align-items: center;
  width: 80%;
  margin: 10px auto;
  padding: 20px 0px;
  font-size: x-large;
  font-weight: bold;
`;
