import Head from "next/head";
import styles from "@/styles/Home.module.css";
import MusicList from "@/components/MusicList";
import styled from "styled-components";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Background>
        <HeaderContainer>🎶 실시간 노래 차트 🎶</HeaderContainer>
        <main className={styles.main}>
          <MusicList />
        </main>
      </Background>
    </>
  );
}

export const Background = styled.div`
  display: flex;
  flex-direction: column;
  width: 100%;
`;

export const HeaderContainer = styled.div`
  display: flex;
  align-items: center;
  width: 80%;
  margin: 10px auto;
  background-color: pink;
  padding: 20px 0px;
  font-size: x-large;
  font-weight: bold;
`;
